"""added clan_id

Revision ID: 414d3a773a25
Revises: 381cfc8f5ad3
Create Date: 2023-08-27 20:34:54.010840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414d3a773a25'
down_revision: Union[str, None] = '381cfc8f5ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('clan_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'clan_id')
    # ### end Alembic commands ###
