"""add_name_column

Revision ID: ce655c52c042
Revises: 414d3a773a25
Create Date: 2023-08-27 21:40:54.696064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce655c52c042'
down_revision: Union[str, None] = '414d3a773a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('name', sa.String(), nullable=False))
    op.add_column('accounts', sa.Column('username', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'accounts', ['username'])
    op.drop_column('accounts', 'clan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('clan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_column('accounts', 'username')
    op.drop_column('accounts', 'name')
    # ### end Alembic commands ###
