"""fix post table ondelete

Revision ID: e734fd993bdf
Revises: cf33ae4d936d
Create Date: 2023-09-02 18:21:59.568357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e734fd993bdf'
down_revision: Union[str, None] = 'cf33ae4d936d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_account_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_account_id_fkey', 'posts', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###
